apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: demo
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ebs-sc
  awsElasticBlockStore:
    volumeID: <your-ebs-volume-id>  # Provide the EBS volume ID if you are manually attaching it
    fsType: ext4

