apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
  namespace: demo
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp3 # General Purpose SSD. You can use io1, st1, or sc1 for other storage types.
reclaimPolicy: Retain

