apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: demo
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None  # This is useful for StatefulSets, but for a basic service, remove if not needed

