apiVersion: v1
kind: Service
metadata:
  name: flaskapi-service
  namespace: flask-namespace
spec:
  selector:
    app: flaskapi
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
